apiVersion: "db.orange.com/v1alpha1"
kind: "CassandraCluster"
metadata:
  name: cassandra
  labels:
    cluster: k8s.kaas
spec:
  baseImage: orangeopensource/cassandra-image
  version: 3.11.4-8u212-0.3.2-release-cqlsh
  configMapName: cassandra-configmap-v1
  dataCapacity: "10Gi"
  dataStorageClass: "rook-ceph-block"
  imagepullpolicy: IfNotPresent
  hardAntiAffinity: false           # Do we ensure only 1 cassandra on each node ?
  deletePVC: true
  autoPilot: false
  gcStdout: true
  autoUpdateSeedList: false
  maxPodUnavailable: 1
  runAsUser: 1000
  resources:
    requests:
      cpu: '1'
      memory: 2Gi
    limits:
      cpu: '1'
      memory: 2Gi
  topology:
    dc:
      - name: dc1
        nodesPerRacks: 1
        labels:
          failure-domain.beta.kubernetes.io/region: us-east-1
        rack:
          - name: rack1
            labels:
              kubernetes.io/hostname: us-east-1.172.26.46.64
          - name: rack2
            labels:
              kubernetes.io/hostname: us-east-1.172.26.46.65
          - name: rack3
            labels:
              failure-domain.beta.kubernetes.io/zone: us-east-1a
